#===================================================
# Description: Build v8 enginer using GitHub Actions
# Author: t1an5t
#===================================================


name: BUILD v8

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    # init ubuntu1804 environment
    - name: init env
      run: |
        sudo apt-get update
        sudo apt-get -y install pkg-config git subversion curl wget build-essential python xz-utils zip p7zip-full
    
#     # get depot_tools
#     - name: depot_tools
#       run: |
#         git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
#         echo export PATH=\"\$PATH:`pwd`/depot_tools/\" >> ~/.bash_profile
    
#     # fetch v8 source code
#     - name: fetch v8
#       run: |
#         source ~/.bash_profile
#         fetch v8
#         cd v8
#         git checkout 7.8.279.23
#         ./build/install-build-deps.sh
 
#     - name: build v8
#       run: |
#         source ~/.bash_profile
#         gclient sync -f
#         tools/dev/v8gen.py x64.release -- v8_enable_disassembler=true v8_enable_object_print=true
#         ninja -C out.gn/x64.release d8
    
