#===================================================
# Description: Build v8 enginer using GitHub Actions
# Author: t1an5t
#===================================================


name: BUILD v8

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    # init ubuntu1804 environment
    - name: init env
      run: |
        sudo apt-get update
        sudo apt-get -y install pkg-config git subversion curl wget build-essential xz-utils zip p7zip-full
    
    # get depot_tools
    - name: depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo export PATH=\"\$PATH:`pwd`/depot_tools/\" >> ~/.bash_profile
        source ~/.bash_profile
        fetch v8
        gclient sync
        cd v8
        git checkout 8.7.220.31
        gclient sync
        ./build/install-build-deps.sh
        tools/dev/v8gen.py x64.release.sample -- v8_enable_disassembler=true v8_enable_object_print=true
        ninja -C out.gn/x64.release.sample v8_monolith
 
    - name: zip depot_tools
      run: |
        zip -q -r depot_tools.zip depot_tools
        zip -q -r v8.zip v8
        
    - name: upload depot_tools
      run: |
        wget https://github.com/Mikubill/transfer/releases/download/v0.4.17/transfer_0.4.17_linux_amd64.tar.gz
        tar -zxvf transfer_0.4.17_linux_amd64.tar.gz
        ./transfer fic --no-progress depot_tools.zip 2>&1 | tee fictransfer.log
        echo "::warning file=1fichier.com::$(cat fictransfer.log | grep https)"
        ./transfer fic --no-progress v8.zip 2>&1 | tee fictransfer.log
        echo "::warning file=1fichier.com::$(cat fictransfer.log | grep https)"
    
